store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegistrationView)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
]

store/users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now

# Create your models here.


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    is_verified_email = models.BooleanField(default=False)
    

class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'EmailVerification object for {self.user.email}'
    
    def send_verification_email(self):
        link = reverse('users:email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = 'Для подтверждения учетной записи для {} перейдите по ссылке: {}'.format(self.user.email, verification_link)
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
            )
    def is_expired(self):
        return True if now() >= self.expiration else False

store/users/forms.py
import uuid
from datetime import timedelta

from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)
from django.utils.timezone import now

from users.models import EmailVerification, User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Введите имя пользователя"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Введите пароль"}))
    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Введите имя"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Введите фамилию"}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Введите имя пользователя"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Введите адрес эл. почты"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Введите пароль"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Подтвердите пароль"}))
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=True)
        expiration = now() + timedelta(hours=48)
        record = EmailVerification.objects.create(code=uuid.uuid4(), user=user, expiration=expiration)
        record.send_verification_email()
        return user

class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email',)

store/users/views.py
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView

from common.views import TitleMixin
from users.forms import UserLoginForm, UserProfileForm, UserRegistrationForm
from users.models import EmailVerification, User

# Create your views here.

class UserLoginView(TitleMixin, TimeoutError, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'Store - Авторизация'
    def get_success_url(self):
        # Перенаправление на профиль пользователя по его pk
        return reverse('users:profile', kwargs={'pk': self.request.user.pk})


class UserRegistrationView(TitleMixin, SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Поздравляем! Вы успешно зарегистрировались!'
    title = 'Store - Регистрация'


class UserProfileView(TitleMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    title = 'Store - Личный кабинет'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.object.id,))


class EmailVerificationView(TitleMixin, TemplateView):
    title = 'Store подтверждение электронной почты'
    template_name = 'users/email_verification.html'
    
    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)
        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVerificationView,self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('index'))
        

store/users/templates/users/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{{ title }}{% endblock %}</title>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> <!-- Подключаем иконки FontAwesome -->
  <style>
    body {
      font-family: 'Roboto', sans-serif;
      background-color: #b4b2b2d3;
      margin: 0;
      padding: 0;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .container {
      background-color: #fff;
      padding: 20px;
      border-radius: 4px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      width: 100%;
      max-width: 400px;
      height: auto;
      margin-top: auto;
      margin-bottom: auto;
    }

    h1 {
      color: #333;
      font-size: 26px;
      margin-bottom: 20px;
      text-align: center;
    }

    label {
      display: block;
      margin-bottom: 8px;
      text-align: left;
    }

    input[type="text"], input[type="email"], input[type="password"] {
      width: 100%;
      padding: 15px;
      margin-bottom: 20px;
      border: 1px solid #777575;
      border-radius: 5px;
      font-size: 14px;
      padding-left: 1px;
    }

    .password-container {
      position: relative;
      padding-right: 4px;
    }

    .password-container input {
      padding-left: 4px;
    }

    .password-container .show-password {
      position: absolute;
      right: 0px; /* Двигаем глазик немного влево */
      top: 50%;
      transform: translateY(-50%);
      cursor: pointer;
    }
    .password-container .key-icon {
      position: absolute;
      right: 30px; /* Ключик размещён левее глазика */
      top: 50%;
      transform: translateY(-50%);
      cursor: pointer;
      font-size: 18px;
      color: #333;
    }

    .btn {
      background-color: #007BFF;
      color: #fff;
      padding: 12px 20px;
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
      transition: transform 0.2s, background-color 0.2s ease;
      margin-bottom: 10px;
      width: 100%;
    }

    .btn:hover {
      transform: scale(1.05);
      background-color: #0056b3;
    }

    .btn-link {
      background-color: transparent;
      color: #007BFF;
      text-decoration: none;
      padding: 0;
      font-size: 14px;
      display: inline-block;
      margin-top: 10px;
    }

    .btn-link:hover {
      text-decoration: underline;
    }

    .forgot-password {
      text-align: left;
      font-size: 14px;
    }

    .forgot-password a {
      color: #007BFF;
      text-decoration: none;
    }

    .forgot-password a:hover {
      text-decoration: underline;
    }

    .social-buttons {
      display: flex;
      justify-content: space-between;
      margin-top: 20px;
    }

    .social-btn {
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: #333;
      color: white;
      padding: 12px 20px;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
      width: 48%;
      transition: transform 0.2s, background-color 0.2s ease;
    }

    .social-btn:hover {
      transform: scale(1.05);
      background-color: #555;
    }

    .social-btn i {
      margin-right: 8px;
    }

    .social-btn.github {
      background-color: #333;
    }

    .social-btn.github a {
    text-decoration: none; /* Убирает подчеркивание */
    color: inherit; /* Задает цвет текста такой же, как у родительского элемента */
    }

    .social-btn.google {
      background-color: #DB4437;
    }

    .social-btn.vk {
      background-color: #4C75A3;
    }

    .social-btn.facebook {
      background-color: #3b5998;
    }
    .form-row {
      display: flex;
      gap: 30px;
    }

    .form-column {
      flex: 1;
    }

    .form-column .form-group {
      margin-bottom: 5px;
    }

    @media (max-width: 768px) {
      .form-row {
        flex-direction: column;
      }
    }
    /* Стиль для успешного уведомления */
    .alert-success {
        background-color: #19eb4a;  /* Зеленый фон */
        color: #155724;  /* Тёмно-зеленый текст */
        border: 1px solid #47ee6e;  /* Светло-зеленая рамка */
    }

    /* Стиль для предупреждающего уведомления */
    .alert-warning {
        background-color: #fff3cd;  /* Желтый фон */
        color: #856404;  /* Желтоватый текст */
        border: 1px solid #ffeeba;  /* Светло-желтая рамка */
    }

    /* Стиль для уведомления */
    .custom-alert {
        position: absolute;
        top: 10px;  /* Убираем отступ от верхней части */
        left: 50%;
        transform: translateX(-50%);
        padding: 12px 18px;
        border-radius: 8px;
        width: auto;
        z-index: 9999;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        font-size: 14px;
        display: flex;
        align-items: center;
        box-sizing: border-box;
    }

    .custom-alert button.close-btn {
        background: none;
        border: none;
        font-size: 18px;  /* Уменьшаем размер крестика */
        color: #856404;  /* Цвет кнопки */
        cursor: pointer;
    }

    .custom-alert button.close-btn:hover {
        color: #dc3545;  /* Цвет при наведении */
    }

    .custom-alert .alert-text {
        flex: 1; /* Это позволяет тексту занимать все доступное пространство */
        text-align: right; /* Выравнивание текста по левому краю */
    }
  </style>
</head>
<body>
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  {% block scripts %}{% endblock %}
  <script>
        // Функция для закрытия уведомления
        function closeAlert() {
    var alert = document.getElementById("custom-alert");
    alert.style.display = "none";  // Скрываем уведомление
    }
  </script>
</body>
</html>

store/users/templates/users/email_verification.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Подтверждение аккаунта</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            font-family: Arial, sans-serif;
            background: #e7eef9;
            background-image: linear-gradient(135deg, rgba(231,238,249,1) 0%, rgba(208,220,239,1) 100%);
        }

        .card {
            text-align: center;
            background: #ffffff;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
            border-radius: 12px;
            padding: 30px;
            max-width: 400px;
            width: 90%;
        }

        .card h1 {
            font-size: 24px;
            color: #333333;
            margin-bottom: 10px;
        }

        .card p {
            font-size: 18px;
            color: #555555;
            margin-bottom: 20px;
        }

        .card .btn {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            color: #ffffff;
            background-color: #4CAF50;
            text-decoration: none;
            border-radius: 8px;
            box-shadow: 0 4px 10px rgba(76, 175, 80, 0.2);
            transition: background-color 0.3s, transform 0.2s;
        }

        .card .btn:hover {
            background-color: #45a049;
            transform: scale(1.05);
        }

        .card .btn:active {
            background-color: #3e8e41;
            transform: scale(1);
        }
    </style>
</head>
<body>
    <div class="card">
        <h1>Поздравляем</h1>
        <p>Ваша учетная запись успешно подтверждена!</p>
        <a href="{% url 'users:login' %}" class="btn">Продолжить</a>
    </div>
</body>
</html>

store/users/templates/users/login.html
{% extends 'users/base.html' %}
{% load socialaccount %}

{% block content %}
<h1>Авторизация</h1>
{% if messages %}
  <div id="custom-alert" class="custom-alert 
    {% for message in messages %}
      {% if message.tags == 'success' %}
        alert-success
      {% else %}
        alert-warning
      {% endif %}
    {% endfor %}">
    <button class="close-btn" onclick="closeAlert()">×</button>
    {% for message in messages %}
      {{ message }}
    {% endfor %}
  </div>
{% elif form.non_field_errors %}
  <div id="custom-alert" class="custom-alert alert-warning">
    <button class="close-btn" onclick="closeAlert()">×</button>
    {{ form.non_field_errors }}
  </div>
{% endif %}
  <form action="{% url 'users:login' %}" method="POST">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

    <div class="form-group">
      <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
      {{ form.username }}
      <!-- <input class="form-control py-4" type="text" id="username" name="username" placeholder="Введите имя пользователя" required> -->
    </div>

    <div class="form-group password-container">
      <label for="{{ form.password.id_for_label }}">Пароль</label>
      {{ form.password }}
      <!-- <input class="form-control py-4" type="password" id="password" name="password" placeholder="Введите пароль" required>  -->
      <span class="show-password" onclick="togglePassword()">👁️</span> <!-- Глазик для показа/скрытия пароля -->
      <span class="key-icon" onclick="autoFillPassword()">🔑</span> <!-- Ключик для автозаполнения пароля -->
    </div>

    <div class="forgot-password">
      <a href="#">Забыли пароль?</a>
    </div>

    <button type="submit" class="btn">Авторизоваться</button>
    
    <div>
      <p>Нужен аккаунт? <a class="btn-link" href="{% url 'users:registration' %}">Зарегистрируйся!</a></p>
    </div>

    <div class="social-buttons">
      <button type="button" class="social-btn github"><i class="fab fa-github"></i><a href="{% provider_login_url 'github' %}">GitHub</a></button>
      <button type="button" class="social-btn google"><i class="fab fa-google"></i> Google</button>
    </div>

    <div class="social-buttons">
      <button type="button" class="social-btn vk"><i class="fab fa-vk"></i>VK</button>
      <button type="button" class="social-btn facebook"><i class="fab fa-facebook"></i> Facebook</button>
    </div>
  </form>
{% endblock %}

{% block scripts %}
  <script>
    // Функция для переключения видимости пароля
    function togglePassword() {
      var passwordField = document.querySelector("[name='password']");
      var passwordIcon = document.querySelector(".show-password");

      if (passwordField.type === "password") {
        passwordField.type = "text";  // Показываем пароль
        passwordIcon.textContent = "🔒"; // Изменяем иконку на закрытый глаз
      } else {
        passwordField.type = "password";  // Скрываем пароль
        passwordIcon.textContent = "👁️"; // Изменяем иконку на открытый глаз
      }
    }

    // Функция для автозаполнения пароля
    function autoFillPassword() {
      var passwordField = document.querySelector("[name='password']");
      passwordField.value = "SavedPassword";  // Здесь можно указать автоматический пароль или заполнить его через браузер
    }
  </script>
{% endblock %}

store/users/templates/users/profile.html
{% extends 'products/base.html' %}
{% load static %}

{% block extra_styles %}
<style>
    .profile-container {
        display: flex;
        gap: 20px;
        max-width: 1200px;
        margin: 20px auto;
        padding: 0 20px;
    }
    .profile-info, .cart {
        background-color: #fff;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 5px;
        flex: 1;
    }
    .profile-info h2, .cart h2 {
        font-size: 20px;
        margin-bottom: 15px;
    }
    .avatar {
        text-align: center;
        margin-bottom: 20px;
    }
    .avatar img {
        width: 100px;
        height: 100px;
        border-radius: 50%;
        border: 1px solid #ddd;
    }
    .form-row {
        margin-bottom: 15px;
    }
    .form-row label {
        display: block;
        margin-bottom: 5px;
        font-size: 14px;
    }
    .form-row input {
        width: 100%;
        padding: 8px;
        border: 1px solid #ddd;
        border-radius: 3px;
        font-size: 14px;
    }
    .save-button {
        background-color: #17a2b8;
        color: #fff;
        border: none;
        padding: 10px 15px;
        border-radius: 3px;
        cursor: pointer;
        margin-top: 10px;
    }
    .save-button:hover {
        background-color: #138496;
    }
    .cart-item {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 15px;
        border-bottom: 1px solid #ddd;
        padding-bottom: 10px;
    }
    .cart-item-controls {
        display: flex;
        gap: 10px;
        align-items: center;
    }
    .cart-item-controls input {
        width: 50px;
        padding: 5px;
        text-align: center;
        border: 1px solid #ddd;
        border-radius: 3px;
    }
    .delete-button {
        background: none;
        border: none;
        color: #dc3545;
        font-size: 18px;
        cursor: pointer;
    }
    .cart-summary {
        display: flex;
        justify-content: space-between;
        margin: 20px 0;
        font-size: 16px;
    }
    .cart-summary span {
        font-size: 18px;
        font-weight: bold;
    }
    .checkout-button {
        background-color: #28a745;
        color: #fff;
        border: none;
        padding: 10px 15px;
        border-radius: 3px;
        width: 100%;
        cursor: pointer;
    }
    .checkout-button:hover {
        background-color: #218838;
    }
    .cart h2{
        text-align: center;
    }
    .cart-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
    }

    .cart-total-quantity {
    font-size: 18px;
    color: #6c757d; /* Темновато-серый цвет */
    background-color: #f8f9fa;
    padding: 5px 10px;
    border-radius: 5px;
    }

    .cart-item-sum {
    font-size: 16px;
    color: #17a2b8; /* Голубоватый цвет */
    margin-top: 10px;
    }

</style>  
{% endblock %}

{% block content %}
<main>
    <div class="profile-container">
        <!-- Левая часть -->
        <div class="profile-info">
            <h2>Профиль</h2>
            <div class="avatar">
                <img src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'images/default_avatar.png' %} {% endif %}" alt="Фото профиля">
            </div>
            <form action="{% url 'users:profile' pk=user.id %}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                <div class="form-row">
                    <label for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name }}
                    <!-- <input class="form-control py-4" type="text" id="first-name" value=""> -->
                </div>
                <div class="form-row">
                    <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name }}
                    <!-- <input class="form-control py-4" type="text" id="last-name" value=""> -->
                </div>
                <div class="form-row">
                    <label for="{{ form.image.id_for_label }}">Выберите изображение</label>
                    {{ form.image }}
                    <!-- <input class="custom-file-input" type="file" id="profile-image"> -->
                </div>
                <div class="form-row">
                    <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username }}
                    <!-- <input class="form-control py-4" type="text" id="username" value=""> -->
                </div>
                <div class="form-row">
                    <label for="{{ form.email.id_for_label }}">Адрес электронной почты</label>
                    {{ form.email }}
                    <!-- <input class="form-control py-4" type="email" id="email" value=""> -->
                </div>
                <button type="submit" class="save-button">Сохранить</button>
            </form>
    </div>
            {% include 'products/baskets.html' %}
        </div>
    </div>
</main>
{% endblock %}

store/users/templates/users/registration.html
{% extends 'users/base.html' %}

{% block content %}
  <h1>Регистрация</h1>
  {% if form.errors %}
  <div id="custom-alert" class="custom-alert alert-warning">
    <button class="close-btn" onclick="closeAlert()">×</button>
    <ul>
      {% for field, errors in form.errors.items %}
        <li><strong>{{ field|capfirst }}:</strong> {{ errors|join:", " }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}
  <form action="{% url 'users:registration' %}" method="POST">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

    <div class="form-row">
      <div class="form-column">
        <div class="form-group">
          <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
          {{ form.username }}
        </div>

        <div class="form-group">
          <label for="{{ form.first_name.id_for_label }}">Имя</label>
          {{ form.first_name }}
        </div>

        <div class="form-group">
          <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
          {{ form.last_name }}
        </div>
      </div>

      <div class="form-column">
        <div class="form-group">
          <label for="{{ form.email.id_for_label }}">Email</label>
          {{ form.email }}
        </div>

        <div class="form-group password-container">
          <label for="{{ form.password1.id_for_label }}">Пароль</label>
          {{ form.password1 }}
          <span class="show-password" onclick="togglePassword()">👁️</span>
        </div>

        <div class="form-group password-container">
          <label for="{{ form.password2.id_for_label }}">Подтвердите пароль</label>
          {{ form.password2 }}
          <span class="show-password" onclick="togglePassword()">👁️</span>
        </div>
      </div>
    </div>
    
    <button type="submit" class="btn">Зарегистрироваться</button>

    <div>
      <p>Уже есть аккаунт? <a class="btn-link" href="{% url 'users:login' %}">Войдите!</a></p>
    </div>

    <div class="social-buttons">
      <button type="button" class="social-btn github"><i class="fab fa-github"></i> GitHub</button>
      <button type="button" class="social-btn google"><i class="fab fa-google"></i> Google</button>
    </div>

    <div class="social-buttons">
      <button type="button" class="social-btn vk"><i class="fab fa-vk"></i> VK</button>
      <button type="button" class="social-btn facebook"><i class="fab fa-facebook"></i> Facebook</button>
    </div>
  </form>
{% endblock %}

{% block scripts %}
  <script>
    function togglePassword() {
      var passwordFields = document.querySelectorAll(".password-container input");
      var passwordIcons = document.querySelectorAll(".password-container .show-password");

      passwordFields.forEach((field, index) => {
        if (field.type === "password") {
          field.type = "text";
          passwordIcons[index].textContent = "🔒"; // Скрыть пароль
        } else {
          field.type = "password";
          passwordIcons[index].textContent = "👁️"; // Показать пароль
        }
      });
    }
  </script>
{% endblock %}